// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvufjqwdqkkpwbuglkma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2dWZqcXdkcWtrcHdidWdsa21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDY1MDEsImV4cCI6MjA2NzQ4MjUwMX0.BNm9xlPH-Bu85A6sC9TG1UvbhynubQDmQiMOU2jJPs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});